version: '3.8'

services:
  api:
    build: .
    container_name: closeai-api
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
    restart: always
    networks:
      - closeai-network

  postgres:
    image: postgres:15
    container_name: closeai-postgres
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - closeai-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: closeai-pgadmin
    depends_on:
      - postgres
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    restart: always
    networks:
      - closeai-network

volumes:
  postgres_data:

networks:
  closeai-network:
    driver: bridge 